name: Download POSTAL 2

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install SteamCMD
        run: |
          sudo add-apt-repository multiverse -y
          sudo dpkg --add-architecture i386

          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections

          sudo apt-get update

          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            steamcmd \
            zip \
            ca-certificates

          sudo ln -sf /usr/games/steamcmd /usr/local/bin/steamcmd

          steamcmd +quit

      - name: Prepare folder
        run: |
          mkdir -p "$HOME/postal2"

      - name: Download POSTAL 2
        env:
          STEAM_USER: ${{ secrets.STEAM_USER }}
          STEAM_PASS: ${{ secrets.STEAM_PASS }}
          STEAM_GUARD: ${{ secrets.STEAM_GUARD }}
        run: |
          if [ -n "$STEAM_GUARD" ]; then

            steamcmd \
              +@sSteamCmdForcePlatformType windows \
              +force_install_dir "$HOME/postal2" \
              +login "$STEAM_USER" "$STEAM_PASS" "$STEAM_GUARD" \
              +app_update 223470 validate \
              +quit

          else

            steamcmd \
              +@sSteamCmdForcePlatformType windows \
              +force_install_dir "$HOME/postal2" \
              +login "$STEAM_USER" "$STEAM_PASS" \
              +app_update 223470 validate \
              +quit

          fi

      - name: Check POSTAL 2
        run: |
          echo "===== POSTAL 2 SIZE ====="
          du -sh "$HOME/postal2"

          echo "===== POSTAL 2 FILES ====="
          find "$HOME/postal2" -maxdepth 3 -type f | head -200

          echo "===== EXE FILES ====="
          find "$HOME/postal2" -iname "*.exe" -type f

      - name: Pack POSTAL 2
        run: |
          cd "$HOME"
          zip -r -1 postal2-windows.zip postal2

      - name: Upload POSTAL 2
        uses: actions/upload-artifact@v4
        with:
          name: POSTAL2-Windows
          path: ~/postal2-windows.zip
          compression-level: 0
          retention-days: 1
